[package]
name = "noise_shader"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bevy = { workspace = true, features = [
    "bevy_core_pipeline",
    "bevy_asset",
    "zstd_rust",
] }
crossbeam-channel = { workspace = true }
bevy_rgb_matrix = { version = "0.1", path = "../../bevy_rgb_matrix" }

[target.'cfg(target_os = "linux")'.dependencies]
rpi-led-matrix = { version = "0.2", optional = true }

[features]
default = ["window"]
window = [
    "bevy/bevy_winit",
    "bevy/bevy_render",
    "bevy/bevy_sprite",
    "bevy/bevy_sprite_render",
    "bevy/x11",
]
matrix = [
    "bevy_rgb_matrix/matrix",
    "rpi-led-matrix",
    "bevy/multi_threaded",
    "bevy/bevy_render",
    "bevy/bevy_sprite",
    "bevy/bevy_sprite_render",
    "bevy/bevy_camera",
    "bevy/bevy_mesh",
    "bevy/bevy_image",
    "bevy/bevy_shader",
    "bevy/bevy_color",
    "bevy/bevy_window",
]
