[workspace]
members = [
    "bevy_rgb_matrix",
    "examples/blink",
    "examples/rotating_3d_cube",
    "examples/noise_shader",
    "examples/metaballs_shader",
]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.17.3", default-features = false }
crossbeam-channel = "0.5"

[profile.dev]
opt-level = 1

[profile.dev-fast]
inherits = "dev"
opt-level = 0

[profile.dev.package."*"]
opt-level = 3
